# Generated by Django 3.0.6 on 2020-11-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='video',
            field=models.FileField(default='default.jpg', upload_to='video/%y'),
        ),
    ]
